### ISSUE TITLE
Not accepting other color

### ISSUE THREAD

**Issue by longpham91** [mapbox/leaflet-image#11]
I was trying to set the polylines on my map to lighter blue, and that worked. But then when I used leaflet-image to capture a picture, it still returned the same standard blue color. Is there anyway to fix this?

**Comment by tmcw** [comment]
Can you give an example? Unless you've set L.PREFER_CANVAS to true, this is just #8

**Comment by longpham91** [comment]
Ok I just realized that now. Sorry.

**Comment by longpham91** [comment]
In the mean time, is there any workaround for this issue?

**Comment by tmcw** [comment]
Works in my testing: please post a full example or testcase.
