### ISSUE TITLE
MarkerCluster, Geojson, CustomStyled markers 'Uncaught Type Error'

### ISSUE THREAD

**Issue by kuyucakli** [mapbox/leaflet-image#13]
I am using markercluster plugin and geojson features with  customized icons: 

var geojsonMarkerOptions = {
            radius: 8,
            fillColor: "#ff7800",
            color: "#000",
            weight: 1,
            opacity: 1,
            fillOpacity: 0.8
        };

When i try to create canvas.toDataURL()  i get uncaught type error on leaflet-image.js:127  --->  ctx.drawImage(root, pos.x, pos.y);

If i do not draw markers everything is fine.

**Comment by tmcw** [comment]
Are you using Leaflet via a CDN or a local copy?

**Comment by kuyucakli** [comment]
I am testing locally with a local copy...

**Comment by tmcw** [comment]
And you have specified `L_PREFER_CANVAS = true;` on your page?

**Comment by kuyucakli** [comment]
Yes i have L_PREFER_CANVAS = true;

**Comment by tmcw** [comment]
Works in my testing. Please provide an accessible test case.

**Comment by esisa** [comment]
I am not sure if this is related or if I am doing something very wrong here. But I have created a test case where if I run createImg(), I get a similar error. If I remove the Geojson layer it works fine. 

https://gist.github.com/esisa/9271338

**Comment by tmcw** [comment]
@esisa you'll need to set `L_PREFER_CANVAS = true;` _before_ you include any Leaflet source code.

**Comment by esisa** [comment]
Aha, I thought it was just before creating the map object. 

Thanks, and sorry about polluting this thread.

**Comment by tmcw** [comment]
Closing, an accessible test case would be needed to debug this.

**Comment by rjawahar** [comment]
Leaflet marker clusters are not getting saved, but saving plain markers have no such issue. Created a demo repo in github for this:

https://github.com/rjawahar/leaflet-image-demo

**Comment by ricaralan** [comment]
I had this same problem

In the new versions of the booklet the constant L_PREFER_CANVAS has now been changed specifying when initializing

map = L.map('map', {**preferCanvas**: true})


I hope to help with this
