### ISSUE TITLE
L.divIcon breaks in marker layer

### ISSUE THREAD

**Issue by bsudekum** [mapbox/leaflet-image#14]
When using `L.divIcon()`, [`handleMarkerLayer()`](https://github.com/mapbox/leaflet-image/blob/gh-pages/leaflet-image.js#L138-L164), breaks because it is looking for a marker image url. 

@tmcw any thoughts how to have this handle this so it can grab a regular div element instead?

**Comment by tmcw** [comment]
Hmm, it's unlikely that this will ever be able to draw divicons, but it shouldn't crash.

**Comment by tmcw** [comment]
https://github.com/mapbox/leaflet-image/pull/15 Should skip them correctly. If you want to try supporting them, go for it - but it won't be easy.

**Comment by tmcw** [comment]
Fixed in #15.

**Comment by robbiet480** [comment]
@tmcw I played around with divIcons and leaflet-headless yesterday. I made little progress. What would you imagine would be involved in implementing this? I hacked together a system using PhantomJS to take a screenshot of a map, but as I said, hacked. 

Any suggestions/guidance would be most appreciated. All work that I do in this regard would be given back to this project/the community.

**Comment by tmcw** [comment]
Getting this to work with divIcons is a particular case of "using javascript to render arbitrary dom elements into images", which is a very hard problem to solve universally.

**Comment by robbiet480** [comment]
That's the path I started going down yesterday. It seems that [fabric.js](http://fabricjs.com/) could be extremely promising, as it allows you to add just about anything to a Canvas layer.

**Comment by tmcw** [comment]
> just about anything\* to a Canvas layer
- except for HTML elements, because they are magnitudes harder than shapes

**Comment by robbiet480** [comment]
[This recently updated Mozilla article](https://developer.mozilla.org/en-US/docs/Web/HTML/Canvas/Drawing_DOM_objects_into_a_canvas) shows how you can draw DOM elements into canvas, so it appears to be possible. I tried to work on this method yesterday, but didn't have time to fully investigate.

**Comment by guspersson** [comment]
Did you ever find a good solution to adding divIcons?

**Comment by tmcw** [comment]
No - I communicate everything on GitHub issues, so if there's no response, there's nothing happening. Rasterizing HTML does not have a silver-bullet fix and thus is unlikely to be included in this library.

**Comment by robbiet480** [comment]
@guspersson We had SVG icons as divIcons. We got around this issue by rendering the icons first to PNG and then replacing the divIcons with those PNG icons.
