### ISSUE TITLE
Work with canvas layers

### ISSUE THREAD

**Issue by bsudekum** [mapbox/leaflet-image#16]
Any ideas on how to get leaflet-image to work with canvas layers specifically @mourner new [leaflet-heatmap plugin](https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-heat/)?

**Comment by tmcw** [comment]
You would need to add another case to the [eachLayer loop](https://github.com/mapbox/leaflet-image/blob/gh-pages/index.js#L22) that checks for instanceof with canvas layers.

**Comment by tmcw** [comment]
Done in 4d8c46acc02ad0b446c7158770a6c408d072c86a
