### ISSUE TITLE
_adjustTilePoint() removed

### ISSUE THREAD

**Issue by dnelson** [mapbox/leaflet-image#19]
Hi,

In tiles.forEach() you call "layer._adjustTilePoint(tilePoint);". This is removed in modern Leaflet versions, e.g. https://github.com/kcl-ddh/leaflet-geowebcache-plugin/pull/1

(not sure if this is a 0.7x or 0.8x change). Commenting out this line seems to fix the error.

**Comment by tmcw** [comment]
Hm. Going to wait until 0.8 is released to sync this to any Leaflet version

**Comment by tmcw** [comment]
This is now safeguarded.
