### ISSUE TITLE
can cache argument be removed from image requests?

### ISSUE THREAD

**Issue by mikelmaron** [mapbox/leaflet-image#20]
We have a number of semi-transparent tile layers. leaflet-image works great, but building the image takes a while, because the addition of a cache argument bypasses the browser cache.

https://github.com/mapbox/leaflet-image/blob/gh-pages/leaflet-image.js#L95

What should we be concerned about if we remove the cache argument in a local copy of the plugin? On some quick tests, everything seems to work ok.

**Comment by tmcw** [comment]
Depends on your browser & tile sources: some browsers will cache the CORS response the got the first time they requested a resource, so you need to re-request the thing with a proper cross-origin flag and a cache-busting string. If it works for you, with a different browser or with same-domain tiles, go for it, but it'll have to stay in this library for safety.
