### ISSUE TITLE
use with leaflet.draw

### ISSUE THREAD

**Issue by jyxt** [mapbox/leaflet-image#21]
EDIT: never mind, I forgot to add  L_PREFER_CANVAS = true;

Hi,

I have both leaflet.draw and leaflet-image plugins enabled. 

When I draw something and try to export, I get:

Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': No function was found that matched the signature provided. 
It looks like root is a svg tag drawn by leaflet.draw, not a image 

``` javascript
function handlePathRoot(root, callback){
    ...
    ctx.drawImage(root, pos.x, pos.y);
    ...
}
```

How do get this to work?

**Comment by tmcw** [comment]
Please [read the readme](https://github.com/mapbox/leaflet-image#requirements).
