### ISSUE TITLE
Use with Leaflet.Label

### ISSUE THREAD

**Issue by r3n4ud** [mapbox/leaflet-image#22]
When using leaflet-image with [the Leaflet.Label plugin](https://github.com/Leaflet/Leaflet.label), the labels generated with `marker.bindLabel('A sweet static label!', { noHide: true })` are not drawn.

I'm not sure if Leaflet.Label support is trivial or not.
A example (probably rails-based) will follow as soon as possible.

**Comment by tmcw** [comment]
Leaflet-label uses HTML to display labels, so it's very non-trivial: leaflet-image can't render HTML to images.
