### ISSUE TITLE
Crashes at line 133

### ISSUE THREAD

**Issue by Akshay-Hegde** [mapbox/leaflet-image#29]
[00:56:04.357] TypeError: Value could not be converted to any of: HTMLImageElement, HTMLCanvasElement, HTMLVideoElement. test/leaflet-image.js:133

133:  ctx.drawImage(root, pos.x, pos.y);

**Comment by tmcw** [comment]
Looks like you have a video element in your map. This is another case that leaflet-image will not be able to handle, but I could possibly get a better error message out of it.

**Comment by Akshay-Hegde** [comment]
Don't know whats going wrong I am using following plugins, I didn't draw rectangle as its not suppored

leaflet.js
leaflet.draw.js
leaflet-providers.js
L.Control.Pan.js  
Leaflet.Search.js
leaflet-areaselect.js
L.Control.Button.js
L.Control.Zoomslider.js 
L.Control.Sidebar.js
leaflet.defaultextent.js
L.Grid.js
leaflet-image.js

Thanks for reply.

**Comment by Akshay-Hegde** [comment]
Hi tmcw "L.Grid.js" has some issue I guess.
