### ISSUE TITLE
tolerate 404 tiles

### ISSUE THREAD

**Issue by tmcw** [mapbox/leaflet-image#4]

**Comment by dnelson** [comment]
Just a comment, as I ran into this problem. I added something like:

```
im.onerror = function(e) {
              e.target.src = "";
            };
```

into loadTile(). But, you are going to end up with an incomplete image/missing tiles. For my use case, I have periodic tiles and the 404 errors were related to indices going out of bounds, without wrapping. So I manually added a periodic wrap to tilePoint.x and tilePoint.y in tiles.forEach(). Pretty hacky but it works.

**Comment by r3n4ud** [comment]
A good solution consists in using the leaflet errorTileUrl, no?

**Comment by r3n4ud** [comment]
OK, it works just fine using:

```
im.onerror = function(e) {
     e.target.src = layer.options.errorTileUrl;
};
```

This works as long as `errorTileUrl` has been defined…

**Comment by r3n4ud** [comment]
Do you accept pull request on this one?

**Comment by tmcw** [comment]
Yep. would need to be something that would work whether or not `errorTileUrl` is defined though.

**Comment by denny123** [comment]
i have same problem and i insert im.onerror and always error like this:
GET http://host/maps/tiles_PSK/7/71/38.png?cache=1415952554127 404 (Not Found)

may be need more insert?

**Comment by hjrobinson** [comment]
In my case it wasn't an issue with the plugin. I just needed to add folders with blank tiles to account for the missing tiles.
