### ISSUE TITLE
Leaflet marker clusters are not getting saved

### ISSUE THREAD

**Issue by rahulgnair91** [mapbox/leaflet-image#40]
Leaflet marker clusters are not getting saved, but saving plain markers have no such issue.
Here is the screenshot of map with marker cluster - ![screenshot from 2015-03-17 11 43 14](https://cloud.githubusercontent.com/assets/9859047/6682223/ffd68970-cc9a-11e4-9fec-a3cb87224c4b.png)
 This is the saved one - ![download 41](https://cloud.githubusercontent.com/assets/9859047/6682225/101a2f44-cc9b-11e4-8bc3-77ca7112ff57.png)

**Comment by tmcw** [comment]
[Please read the readme](https://github.com/mapbox/leaflet-image#requirements): SVG & HTML elements are not supported.

**Comment by rahulgnair91** [comment]
Thanks, I tried html2canvas plugin along with leaflet-image and generated the screenshot - 
![download 92](https://cloud.githubusercontent.com/assets/9859047/6688821/612c9638-ccdc-11e4-854f-7f5330966702.png)

**Comment by juansh20** [comment]
Hello rahulgnair91, how did you do it?.

**Comment by sachinp-git** [comment]
Hi @rahulgnair91  Can you please tell how did you achieve this using html2canvas.

**Comment by sertceps** [comment]
"dome-to-image" is ok for me.
