### ISSUE TITLE
Issue when using L.icon image as marker

### ISSUE THREAD

**Issue by EricSarmany** [mapbox/leaflet-image#41]
If a .png image is used as a marker, leaflet-image fails as follows:

```
leaflet-image.js (line 194, col 59)
TypeError: size.divideBy is not a function

anchor = L.point(options.iconAnchor || size && size.divideBy(2, true))
```

The marker displays fine on the original map in the browser.

**Comment by tmcw** [comment]
are you supplying an L.point for your icon's size?

**Comment by EricSarmany** [comment]
Here's a sample code excerpt I'm using for an image marker:

```
var marker = L.marker([31.767, -106.424], {
  icon: L.icon({
    iconUrl: 'icon.png',
    iconSize: [16, 16]
  })
});
```

**Comment by pvernier** [comment]
I had the same issue with icons of any formats, not just .png.
I resolved it by replacing the folllowing code:

``` javascript
anchor = L.point(options.iconAnchor || size && size.divideBy(2, true)),
x = pos.x - size[0] + anchor.x,
y = pos.y - anchor.y;
```

with:

``` javascript
x = pos.x - size[0] + size[0]/2,
y = pos.y - size[1]/2;
```

**Comment by EricSarmany** [comment]
That fix worked. Thanks Pierre!

**Comment by daamsie** [comment]
I was using pvernier's fix, but this ignores the iconAnchor and that eventually caused problems. The following is working for me now: 

```
x = pos.x - size[0] + (typeof options.iconAnchor == 'object' ? options.iconAnchor[0] : size[0]/2),
y = pos.y - (typeof options.iconAnchor == 'object' ? options.iconAnchor[1] : size[1]/2);
```

**Comment by tmcw** [comment]
Closing; happy to accept a pull request of one of the proposed changes.
