### ISSUE TITLE
`L.TileLayer.Canvas` is not available in leaflet master

### ISSUE THREAD

**Issue by jieter** [mapbox/leaflet-image#42]
Another leaflet API change causing errors with leaflet-image:

```
TypeError: Expecting a function in instanceof check, but got [object Object]
at handleTileLayer (<path>/leaflet-image/index.js:60:56)
...
```

Problem is in https://github.com/mapbox/leaflet-image/blob/gh-pages/index.js#L60, as `L.TileLayer.Canvas` is removed from leaflet: 'Removed `TileLayer.Canvas` in favor of the much more flexible and powerful `GridLayer`.`

No completed yet, keeping backwards compatibility is easy, but it seems we now need to check each tile it it's canvas?

ref: Leaflet/Leaflet#3163

**Comment by jieter** [comment]
This might be it, but it's not very well tested yet: https://github.com/mapbox/leaflet-image/compare/gh-pages...jieter:fix-leaflet-master

Do you want to keep it backwards compatible with 0.7.3 or should we start with a separate branch to track leaflet-0.8/1.0

**Comment by tmcw** [comment]
Definitely want to make an 0.8/1.0-compatible leaflet-image as a new, non-backwards-compatible semver major version bump. When 1.0 lands, it'll eliminate a lot of cruft in this library and likely prompt a rewrite.

**Comment by jieter** [comment]
So should I open a PR?

**Comment by mrohnstock** [comment]
would be great to have a working plugin, when leaflet 1.0 final is out!

**Comment by derwaldgeist** [comment]
I am using Leaflet as part of a Meteor package which is already on Leaflet 1.0.0-beta2. Is there any chance to make leaflet-image work with this beta version? I ran into the issue that L.TileLayer.Canvas is not defined.

**Comment by ClaudioCas** [comment]
leaflet 1.0 beta 2 is out, but the plugin still no compatible.
Any update about this issue?

**Comment by tmcw** [comment]
Please open a PR if you want to see this happen.

**Comment by tmcw** [comment]
Tested in 6ea4f54c5cfbc01d6697fc3d587eb11c51dfb766
