### ISSUE TITLE
jpg images?

### ISSUE THREAD

**Issue by mgincnj** [mapbox/leaflet-image#43]
Is there a way to export jpg images instead of png?

**Comment by tmcw** [comment]
I think this should be pretty simple, queuing up to add.

**Comment by tmcw** [comment]
Actually, no: leaflet-image returns a canvas, so this is in your court rather than the API's.

Instead of `canvas.toDataURL();` run `img.src = canvas.toDataURL('image/jpeg');` See [the docs for toDataURL](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL) for the details.
