### ISSUE TITLE
catch wms layer

### ISSUE THREAD

**Issue by EraSiuS** [mapbox/leaflet-image#44]
I'm using leaflet-image with osm layer and my own wms layer from geoserver.
I can't catch geoserver wms layer.
My mws call : 

L.tileLayer.wms('http://IP:PORT/geoserver/wms' .....
My layer is displayed on leaflet without problem but not on image generated from leaflet-image.
And no error displayed on console.
Anybody have try this ?

Thanks for your help

**Comment by tmcw** [comment]
[Does your WMS provider support CORS](https://github.com/mapbox/leaflet-image#requirements)?

**Comment by tmcw** [comment]
Closing; your wms server probably doesn't support CORS.
