### ISSUE TITLE
TypeError: i is undefined

### ISSUE THREAD

**Issue by mgincnj** [mapbox/leaflet-image#45]
Trying to use leaflet-image to render a map.  When I do so, I get a TypeError: i is undefined in mapbox.js line 57.

To reproduce the error:

http://maps.wildtroutstreams.com/COtest3.html

click on the custom control that looks like a circle with a pin coming out (tooltip: Add Export Placemarks)

Scroll to the bottom, if need be, and click on the "snapshot" button

**Comment by tmcw** [comment]
needs a clearer traceback.
