### ISSUE TITLE
TypeError: Argument 1 of CanvasRenderingContext2D.drawImage

### ISSUE THREAD

**Issue by omnivl** [mapbox/leaflet-image#46]
Any idea why this is occuring?

**Comment by tmcw** [comment]
I'd need more information, like example code, to debug this.

**Comment by Kulikovpavel** [comment]
Get same error.

Code as in example

```
leafletImage(map, function(err, canvas) {
    // now you have canvas
    // example thing to do with that canvas:
    var img = document.createElement('img');
    var dimensions = map.getSize();
    img.width = dimensions.x;
    img.height = dimensions.y;
    img.src = canvas.toDataURL();
    document.getElementById('images').innerHTML = '';
    document.getElementById('images').appendChild(img);
});
```

Map - leaflet.

 Argument 1 of CanvasRenderingContext2D.drawImage could not be converted to any of: HTMLImageElement, HTMLCanvasElement, HTMLVideoElement.

**Comment by tmcw** [comment]
The important part is what's in the map: see the [requirements](https://github.com/mapbox/leaflet-image#requirements) - do you have any non-tile layers in the map?

**Comment by omnivl** [comment]
Ok got it... Was trying to get polys and markers as well
