### ISSUE TITLE
marker cluster

### ISSUE THREAD

**Issue by zipzapduo** [mapbox/leaflet-image#48]
If used with marker cluster i get undefined?cache=false on method handleMarkerLayer(marker, callback)

**Comment by tmcw** [comment]
Please provide a jsfiddle to debug this issue.

**Comment by tmcw** [comment]
Same as https://github.com/mapbox/leaflet-image/issues/40 - noted in dac626b2963a95276fb1ddb6da2a445a9b495812 - marker clusters are not supported.
