### ISSUE TITLE
Images generated from L.map don't seem to work

### ISSUE THREAD

**Issue by nathanathan** [mapbox/leaflet-image#6]
I tried the example map on the leafletjs home page and I was unable to render tiles from it:

``` javascript
// create a map in the "map" div, set the view to a given place and zoom
var map = L.map('map').setView([51.505, -0.09], 13);

// add an OpenStreetMap tile layer
L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);

// add a marker in the given location, attach some popup content to it and open the popup
L.marker([51.5, -0.09]).addTo(map)
    .bindPopup('A pretty CSS3 popup. <br> Easily customizable.')
    .openPopup();
```

This ability would be very useful to me. I have a SO question here that explains why I need it:
http://stackoverflow.com/questions/18939115/generating-redistributable-map-images-without-a-server

I put a small bounty on this issue, I hope anyone else who is interested will join in on it:
https://www.bountysource.com/issues/949403-images-generated-from-l-map-don-t-seem-to-work

**Comment by tmcw** [comment]
Fixed in 38d72270bc914fb341d992ec0c6eedb575366875

Markers from the Leaflet CDN are not supported because the Leaflet CDN doesn't support CORS. Otherwise OSM layers should be fine.

**Comment by nathanathan** [comment]
:smile: Thanks! The bounty is yours if you want it.

**Comment by tmcw** [comment]
No thx :) https://supporters.eff.org/donate
