### ISSUE TITLE
Using markers with data URL as a src fails

### ISSUE THREAD

**Issue by daamsie** [mapbox/leaflet-image#60]
After digging into this, the problem is due to the addition of the cache busting addCacheString() function. The image never loads and as a result, the im.onLoad handler is never triggered. 

There needs to be a way to turn off addCacheString, or just disable it altogether when the src is a data URL. As there are no CORS concerns with data URLs, I can't see the need for it in that scenario.

**Comment by tmcw** [comment]
Fixed in #64
