### ISSUE TITLE
Subpixel placement of marker images results in blurry rendering

### ISSUE THREAD

**Issue by daamsie** [mapbox/leaflet-image#61]
Marker positions are calculated automatically and this usually results in subpixel placements, which in turn results in blurry rendering.

My solution locally is to round the x and y in the handleMarkerLayer function

```
x = Math.round(pos.x - size[0] + anchor.x),
y = Math.round(pos.y - anchor.y);
```

I am not sure if there are any unintended consequences from doing that, but the result is much crisper markers. 

See the two generated images for comparison. 

![screenshot-6-rounded](https://cloud.githubusercontent.com/assets/740324/13800842/dc87f1a6-eb80-11e5-9790-e5bfc2e39722.png)
![screenshot-6-unrounded](https://cloud.githubusercontent.com/assets/740324/13800843/dc8c24c4-eb80-11e5-9d2b-f3af8e1dc5f1.png)

**Comment by tmcw** [comment]
Fixed in #64
