### ISSUE TITLE
Integrate with leaflet-label

### ISSUE THREAD

**Issue by panzors** [mapbox/leaflet-image#62]
https://github.com/Leaflet/Leaflet.label

Not sure if this will be with you guys or the other library but these two libraries don't work well together.
Markers will render, but it doesn't render the text along with it. 

Recommendations? 
Thanks in advance.

**Comment by tmcw** [comment]
See [the requirements](https://github.com/mapbox/leaflet-image#requirements). Leaflet.label uses HTML elements, and this library does not and cannot rasterize them.
