### ISSUE TITLE
plugin not working when there is a linestring on the map

### ISSUE THREAD

**Issue by Luke-Tan** [mapbox/leaflet-image#67]
Hi, I have tested using this plugin with this code 
var lines=[{
      "type" : "LineString",
      "coordinates" : [[-10.833305983642491, -48.515625],       [10.833305983642491,-17.2265625]]
    }];

var linesLayer=L.geoJson(lines);

linesLayer.addTo(map);
after this code has been run, the leafletImage function is no longer able to run. any idea what is the problem?

**Comment by tmcw** [comment]
Have you read the requirements https://github.com/mapbox/leaflet-image#requirements especially the one about L_PREFER_CANVAS?

**Comment by Luke-Tan** [comment]
yes but I didn't really understand what it meant. Could you help to explain it to me?

**Comment by tmcw** [comment]
> (Leaflet < 1.0.0) You must set L_PREFER_CANVAS = true; so that vector layers are drawn in Canvas

If you're using a non-beta version of Leaflet, you need to set the variable `L_PREFER_CANVAS = true;` before the rest of your code.

**Comment by Luke-Tan** [comment]
Hmm it doesn't seem to fix the issue though. I have a fiddle here with the issue https://jsfiddle.net/w83g6vzq/

**Comment by Luke-Tan** [comment]
nevermind I am stupid... I just included that line at a wrong place in my code
