### ISSUE TITLE
base64 dataurl as img src not working

### ISSUE THREAD

**Issue by Luke-Tan** [mapbox/leaflet-image#68]
From what I know, markers not being supported due to a CORS related issue is one which would not affect a local base64 image URL, but leafletimage fails to render when there are markers with such images as their src. Is this an issue which is fixable?

**Comment by tmcw** [comment]
Data urls should work. What kind of marker are you using? L.marker is supported, L.divIcon is not.

**Comment by Luke-Tan** [comment]
here is a fiddle with the issue, https://jsfiddle.net/w83g6vzq/3/, console seems to give the error

leaflet-image.js:165 GET data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAUAAAAHCCAYAAACe6BB5AAAAAXNSR…BBAgLwIBXPESDQhMDm5kbxcf4/937yFW0Ts9EAAAAASUVORK5CYII=?cache=1460622117755 net::ERR_INVALID_URL

**Comment by Luke-Tan** [comment]
Nevermind, just realised this issue was already fixed and cdn just has an outdated version of leaflet-image.js
