### ISSUE TITLE
Error when rendering the whole world

### ISSUE THREAD

**Issue by nathanathan** [mapbox/leaflet-image#7]
When zoom out far enough to see the gray border above and below the world map then try to render nothing is shown and I see the following error in my console:

```
GET http://b.tiles.mapbox.com/v3/tmcw.map-u4ca5hnt/0/0/-1.png?cache=1379970765170 404 (Not Found) leaflet-image.js:105
Cross-origin image load denied by Cross-Origin Resource Sharing policy. 
```

**Comment by tmcw** [comment]
Cool, probably requires a `.wrap()`...
