### ISSUE TITLE
Fails with leaflet 1.0 due to lack of L.tileLayer.canvas

### ISSUE THREAD

**Issue by abenrob** [mapbox/leaflet-image#71]
When upgrading leaflet to 1.0, found an error:
TypeError: Expecting a function in instanceof check, but got undefined
This is coming from [here](https://github.com/mapbox/leaflet-image/blob/gh-pages/leaflet-image.js#L63) where the check for instanceof is failing as L.tileLayer.cavas does not exist in [leaflet 1.0](http://leafletjs.com/reference-1.0.0.html#tilelayer).

**Comment by tmcw** [comment]
6ea4f54c5cfbc01d6697fc3d587eb11c51dfb766 tests the 1.0 compatibility.
