### ISSUE TITLE
[0.2.0 & leaflet 0.7.7] Cannot read property 'tileLayer' of undefined

### ISSUE THREAD

**Issue by mrohnstock** [mapbox/leaflet-image#72]
[hasMapbox](https://github.com/mapbox/leaflet-image/blob/e1856ab59b7613e007d8981019a0150bb3581687/leaflet-image.js#L11) is `true`, when `L.mapbox` is undefined.

The check on [lines 84-85](https://github.com/mapbox/leaflet-image/blob/e1856ab59b7613e007d8981019a0150bb3581687/leaflet-image.js#L84) checks for an instance of `layer` in `L.mapbox`, which is undefined in my case.

**Comment by jieter** [comment]
just ran into this too, while updating leaflet-image in leaflet-headless... Why isn't this caught by the [one-point-oh.html test page](https://github.com/mapbox/leaflet-image/blob/gh-pages/test/pages/one-point-oh.html)?

edit: Test image only shows white, not the tile layer.
