### ISSUE TITLE
Element could not be drawn on canvas 

### ISSUE THREAD

**Issue by majadinjar** [mapbox/leaflet-image#74]
I got this console.log error, tried to get image of points and polygon?

**Comment by jieter** [comment]
Are you using the canvas renderer:

> (Leaflet < 1.0.0) You must set L_PREFER_CANVAS = true; so that vector layers are drawn in Canvas
> (Leaflet >= 1.0.0) You must set renderer: L.canvas() for any layer that you want included in the generated image.

**Comment by majadinjar** [comment]
Thanks!

**Comment by jieter** [comment]
What version of Leaflet do you use? 

> (Leaflet < 1.0.0) You must set L_PREFER_CANVAS = true; so that vector layers are drawn in Canvas

you must add `<script>L_PREFER_CANVAS = true;</script>` before including leaflet.

> (Leaflet >= 1.0.0) You must set renderer: L.canvas() for any layer that you want included in the generated image.

You can use the [`preferCanvas: true` map option](http://leafletjs.com/reference-1.0.0.html#map-prefercanvas)

**Comment by majadinjar** [comment]
I managed to succeed, now it's saying only : 

> Image from origin 'file://' has been blocked from loading by Cross-Origin Resource Sharing policy: Invalid response. Origin 'null' is therefore not allowed access.
