### ISSUE TITLE
L.divIcon Markers Fatally Err. 

### ISSUE THREAD

**Issue by workmaps** [mapbox/leaflet-image#81]
Greetings, 
I am using L.divIcon to create lables a la http://www.coffeegnome.net/labels-in-leaflet/ . When the labels are on I get a fatal error:

Uncaught TypeError: Cannot read property 'match' of undefined in index.js at line 211. 

It work just fine with the labels off though. 

Thanks, Tyler

**Comment by tmcw** [comment]
https://github.com/mapbox/leaflet-image#requirements - please read the readme.

**Comment by workmaps** [comment]
I read and understand the documentation. My expectation from reading the documentation was that the divIcons would not be included in the output. I did not expect that the application would fatally err. Is there any interest in handling that error?

Thanks, Tyler
