### ISSUE TITLE
Is leaflet-image compatible with Ionic? undefined is not an object (evaluating 'url.match')

### ISSUE THREAD

**Issue by metalaureate** [mapbox/leaflet-image#84]
When using leaflet-image with the Ionic platform, I get the error:

`TypeError: undefined is not an object (evaluating 'url.match')`

In function layersDone, line 58

(Latest github repo version).

Any clues?

```
   leafletImage(map, function (err, canvas) {
      // now you have canvas
      // example thing to do with that canvas:
      var img = document.createElement('img');
      var dimensions = map.getSize();
      img.width = dimensions.x;
      img.height = dimensions.y;
      img.src = canvas.toDataURL();
      document.getElementById('images').innerHTML = '';
      document.getElementById('images').appendChild(img);
    });
```

**Comment by metalaureate** [comment]
I got it to work if I removed all the geoJSON layers on the map. I'm assuming it is not compatible with geoJSON layers?

**Comment by tmcw** [comment]
Committed a workaround. I can't confirm that it'll work for your usecase without a complete testcase: if it doesn't, please try your hand at fixing the issue.
