### ISSUE TITLE
Extremely slow

### ISSUE THREAD

**Issue by vince1995** [mapbox/leaflet-image#87]
Hi,

is it normal that calling the function is extremely slow? It's needing ~8 seconds.

The code:
`leafletImage(g.invisibleMap, function(err,canvas){
var end = Date.now();
console.log(end-start);
}`

I just have a polyline on the map like this:
![image](https://cloud.githubusercontent.com/assets/15120985/18676062/a7e65f10-7f54-11e6-82de-f49891eee094.png)

**Comment by tmcw** [comment]
Yep, in order to work around certain CORS bugs, leaflet-image reloads all of the tiles in your map's viewport. Depending on the speed of the servers you're using for maps, those requests can be slow, and the latency of those requests is the only performance-intensive part of the code.

**Comment by vince1995** [comment]
Solved it with another tile server and cache plugin.
