### ISSUE TITLE
An option for excluding a TileLayer from rendering

### ISSUE THREAD

**Issue by ka7eh** [mapbox/leaflet-image#95]
I didn't see any way in the code to exclude specific layers from being converted to image.
In my case, I'd like to only render my basemap and not the overlays.

**Comment by tmcw** [comment]
Could you temporarily remove the overlays in your own code before running leaflet-image and add them back once the image is rendered?

**Comment by ka7eh** [comment]
Actually as a quick workaround, I added an `options` argument to the `leafletImage` function to exclude TileLayers. Check here: https://github.com/ka7eh/leaflet-image/tree/add-layer-exclusion-option

If it looks like a reasonable approach, I can make a PR and then improve and expand the `options` argument from there.

**Comment by tmcw** [comment]
Thoughts on the approach I proposed? Features are bugs, and I don't think this justifies a code change when it has a simple workaround that doesn't require leaflet-image to change.

**Comment by ka7eh** [comment]
Sure, that'll do for now. Thanks.
